# Generated by Django 4.1 on 2022-09-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_delete_users_remove_tramites_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramites',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
