# Generated by Django 4.1 on 2022-09-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_tramites_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramites',
            name='completed_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
