# Generated by Django 4.1 on 2022-09-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_tramites_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramites',
            name='solicitante',
            field=models.CharField(default='Sin datos', max_length=255),
        ),
    ]
